### ISSUE TITLE
Can‘t use admin@example.com to login the /admin

### ISSUE THREAD

**Issue by SpiffyEight77** [joshua5201/tioj#25]
Can‘t use username: admin@example.com and the password: password to login the /admin

I'm a Ruby beginner and I'm also writting the OJ for my school.......

**Comment by joshua5201** [comment]
Hello, this is an old project and I don't remenber that we have a default password.
But you can try to register user and set it as admin in rails console.
 
If you want to learn Ruby / Rails, this is not a good example (a lot of anti-pattern and old stuffs we made at 3rd grade of high school ). If you have questions of Ruby / Rails, feel free to email me! ( in either English, Chinese or Japanese)
